--- 
- name: NVIDIA CUDNN for Redhat 7
  block:

    - name: Install Nvidia CUDNN for RedHat 7
      yum:
        name:
          - libcudnn8
          - libcudnn8-devel

  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '7'


- name: NVIDIA CUDNN for Ubuntu 20
  block:

    - name: Install Nvidia CUDNN for Ubuntu 20
      apt:
        name:
          - libcudnn8
          - libcudnn8-dev

  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '20'
