--- 
- name: Install NCCL from CUDA repository for RHEL
  yum:
    name:
      - "libnccl-{{ nccl_package_version }}"
      - "libnccl-devel-{{ nccl_package_version }}"
      - "libnccl-static-{{ nccl_package_version }}"
    state: latest
  environment: "{{proxy_env if proxy_env is defined else {}}}"
  when:
    - ansible_os_family == 'RedHat'

- name: Install NCCL from CUDA repository for Ubuntu 20
  apt:
    name:
      - "libnccl2={{ nccl_package_version }}"
      - "libnccl-dev={{ nccl_package_version }}"
    state: present
  environment: "{{proxy_env if proxy_env is defined else {}}}"
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '20'