---
- name: Packages for RHEL 7
  block:
 
    - name: Ensure latest microcode_ctl is installed
      yum:
        name:
          - microcode_ctl
        state: latest

    - name: Ensure dracut early_microcode="yes" is configured
      lineinfile:
        path: /usr/lib/dracut/dracut.conf.d/01-microcode.conf
        regexp: '^early_microcode='
        line: 'early_microcode="yes"'
        create: no
        state: present

    - name: Install development tools
      yum:
        enablerepo: "*developer_EPEL*"
        name:
          - "@Development Tools"
          - numactl
          - numactl-devel
          - libxml2
          - binutils-devel
          - environment-modules
        state: latest

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
      when:
        - "options is defined"
        - "'upgrade' in options"

    - name: Reboot to install kernel updates
      reboot:
        reboot_timeout: 900
      when:
        - "options is defined"
        - "'upgrade' in options or 'rhck' in options"

  when: 
    - ansible_os_family == 'RedHat' 
    - ansible_distribution_major_version == '7'


- name: Packages for Ubuntu 20
  block:

    - name: Ensure Oracle Cloud Agent is stopped to prevent running apt
      systemd:
        name: snap.oracle-cloud-agent.oracle-cloud-agent
        state: stopped

    - name: Wait for automatic system updates to complete
      shell: while pgrep apt; do sleep 10; done;

    - name: Disable unattended-upgrades
      systemd:
        name: unattended-upgrades
        enabled: no
        state: stopped
        masked: yes

    - name: Update apt-get repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        name: '*'
        state: latest
      when:
        - "options is defined"
        - "'upgrade' in options"

    - name: Reboot to install kernel updates
      reboot:
        reboot_timeout: 900
      when:
        - "options is defined"
        - "'upgrade' in options"

    - name: Ensure Oracle Cloud Agent is stopped to prevent running apt
      systemd:
        name: snap.oracle-cloud-agent.oracle-cloud-agent
        state: stopped

    - name: Wait for automatic system updates to complete
      shell: while pgrep apt; do sleep 10; done;

  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '20'
