---
- name: create perftest directory
  file:
    path: "{{ benchmark_base_path }}/perftest"
    state: directory
    mode: 0755
    owner: opc
    group: opc
  become: yes

- name: clone IB perftest
  git:
    repo: "{{ perftest_repo }}"
    dest: "{{ benchmark_base_path }}/perftest"
    force: yes
  become_user: opc

- name: autogen IB perftest
  command: ./autogen.sh
  args:
    chdir: "{{ benchmark_base_path }}/perftest"

- name: configure IB perftest for GPUDirect
  command: ./configure CUDA_H_PATH=/usr/local/cuda/include/cuda.h
  args:
    chdir: "{{ benchmark_base_path }}/perftest"

- name: build IB perftest
  make:
    chdir: "{{ benchmark_base_path }}/perftest"
#    jobs: 4
