---

- block:

  - name: Create module directory
    file:
      path: /etc/modulefiles/mpi/intel
      state: directory

  - name: Install supporting packages for Intel platform compliance
    yum:
      state: latest
      name:
        - mesa-libGLU
        - libICE
        - libSM
        - libXt
        - libXtst

  - name: Intel Repo Key
    rpm_key:
      state: present
      key: https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB

  - name: Intel Repo Key
    rpm_key:
      state: present
      key: https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB

  - name: Intel PSXE runtimes KEY
    rpm_key:
      state: present
      key: https://yum.repos.intel.com/2020/setup/RPM-GPG-KEY-intel-psxe-runtime-2020

  - name: intel-oneAPI
    yum_repository:
      name: oneAPI
      description: Intel(R) oneAPI repository
      baseurl: https://yum.repos.intel.com/oneapi
      enabled: 0
      gpgcheck: 1
      gpgkey: https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB

  - name: Install Intel libraries
    yum:
      state: latest
      name:
        - intel-oneapi-mpi
        - intel-oneapi-mkl
      enablerepo: "oneAPI"

  - name: Create MPI directory
    file:
      path: /etc/modulefiles/intel/
      state: directory

  - name: generate module files
    ansible.builtin.shell:
      cmd: /opt/intel/oneapi/modulefiles-setup.sh --output-dir=/etc/modulefiles/intel/ --force
      chdir: /opt/intel/oneapi/
