---

- block:

  - name: Create module directory
    file:
      path: /etc/environment-modules/modules/intel/
      state: directory

  - name: Intel Repo Key
    apt_key:
      url: https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
      state: present
    # ignore errors because of multiple keys
    ignore_errors: yes

  - name: Intel oneAPI Repository
    apt_repository:
      repo: deb https://apt.repos.intel.com/oneapi all main
      state: present

  - name: Add PXSXE repo
    apt_repository:
      repo: deb https://apt.repos.intel.com/2020 intel-psxe-runtime main
      state: present

  - name: Install Intel oneAPI
    apt:
      state: latest
      update_cache: yes
      name:
        - intel-oneapi-mpi
        - intel-oneapi-mkl

#  - name: Install PSXE runtime
#    apt:
#      state: latest
#      name:
#        - intel-psxe-runtime

  - name: generate module files
    ansible.builtin.shell:
      cmd: /opt/intel/oneapi/modulefiles-setup.sh --output-dir=/etc/environment-modules/modules/intel/ --force
      chdir: /opt/intel/oneapi/
