--- 
- name: Disable nozeroconf network routes for RedHat
  block:

  - name: Ensure NOZEROCONF is configured
    lineinfile:
      path: /etc/sysconfig/network
      line: NOZEROCONF=yes
      state: present

  when: 
    - ansible_os_family == 'RedHat'
