---
- name: install tuned via apt
  apt: name=tuned state=latest update_cache=yes
  ignore_errors: True  

- name: start tuned
  service: name=tuned state=started enabled=yes
  ignore_errors: True

- name: start-profile
  shell: tuned-adm profile throughput-performance
  ignore_errors: True
