---
- name: Disable SELinux for RedHat 7
  block:

    - name: Ensure SELinux configuration is disabled
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
        create: no
        state: present

  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '7'
