hpc_artifacts_download: "https://objectstorage.eu-frankfurt-1.oraclecloud.com/p/iJegsGWkNqcoGo2912-MDHSyGozef8jUiPKZO3PcAvfntWRMpt_sy-uCBKRj6Egl/n/hpc/b/source/o/"
rhck_kernel_level: "3.10.0-1160"
install_prefix: "/opt"
benchmark_base_path: "{{ install_prefix }}/oci-hpc"
perftest_repo: https://github.com/linux-rdma/perftest.git
nccltest_repo: https://github.com/NVIDIA/nccl-tests.git
gpuburn_repo: https://github.com/wilicc/gpu-burn.git
spack_repo: "https://github.com/spack/spack.git"
spack_base_path: "{{ install_prefix }}/spack"
gcc_version: 11.2.0
