---
grub_cmdline:
  - processor.max_cstate=1
  - intel_idle.max_cstate=0
  - mce=ignore_ce
  - nohz=off
  - skew_tick=1
  - iommu=pt
  - numa_balancing=disable
grub_cmdline_disable_mitigations:
  - noibrs
  - noibpb
  - nopti
  - nospectre_v2
  - nospectre_v1
  - l1tf=off
  - nospec_store_bypass_disable
  - no_stf_barrier
  - mds=off
  - mitigations=off
grub_cmdline_enroot:
  - namespace.unpriv_enable=1
  - user_namespace.enable=1
grub_cmdline_network_device_names:
  - oci_hpc.rdma_device_names_mode=2
  - oci_hpc.vnic_device_names_mode=1
kernel_limits:
  - { name: "memlock",   type: "soft",  limit: "unlimited" }
  - { name: "memlock",   type: "hard",  limit: "unlimited" }
  - { name: "rss",       type: "soft",  limit: "unlimited" }
  - { name: "rss",       type: "hard",  limit: "unlimited" }
  - { name: "core",      type: "soft",  limit: "unlimited" }
  - { name: "core",      type: "hard",  limit: "unlimited" }
  - { name: "maxlogins", type: "soft",  limit: "8192" }
  - { name: "maxlogins", type: "hard",  limit: "8192" }
  - { name: "stack",     type: "soft",  limit: "unlimited" }
  - { name: "stack",     type: "hard",  limit: "unlimited" }
  - { name: "nproc",     type: "soft",  limit: "2067554" }
  - { name: "nproc",     type: "hard",  limit: "2067554" }
  - { name: "nofile",    type: "soft",  limit: "5000000" }
  - { name: "nofile",    type: "hard",  limit: "5000000" }
