---
- name: Ensure sshd allowed MAC algorithms are present
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^(\s*)(?i)MACs'
    line: 'MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,umac-128@openssh.com'
    state: present
  notify:
  - sshd restart

- name: Ensure sshd allowed cipher algorithms are present
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^(\s*)(?i)Ciphers'
    line: 'Ciphers aes256-ctr,aes192-ctr,aes128-ctr'
    state: present
  notify:
  - sshd restart

- name: Ensure sshd allowed HostKeyAlgorithms are present
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^(\s*)(?i)HostKeyAlgorithms'
    line: 'HostKeyAlgorithms ssh-ed25519,ecdsa-sha2-nistp384,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ecdsa-sha2-nistp521'
    state: present
  notify:
  - sshd restart

- name: Ensure sshd allowed KexAlgorithms are present
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^(\s*)(?i)KexAlgorithms'
    line: 'KexAlgorithms ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha256'
    state: present
  notify:
  - sshd restart
