---
- name: OCI HPC packages for RHEL 7
  block:

    - name: Install oci-cn-auth (HPC)
      yum:
        name: "{{ hpc_artifacts_download }}oci-cn-auth-{{ oci_cn_auth_version }}-compute.el7.noarch.rpm"
        enablerepo: "*developer_EPEL*"
        state: present
        disable_gpg_check: yes

    - name: Stop oci-cn-auth renew timer
      systemd:
        name: oci-cn-auth-renew.timer
        state: stopped
        enabled: yes

    - name: Install oci-hpc-mlx-configure (HPC)
      yum:
        name: "{{ hpc_artifacts_download }}oci-hpc-mlx-configure-{{ oci_hpc_mlx_configure_version }}-compute.el7.noarch.rpm"
        state: present
        disable_gpg_check: yes

    - name: Install oci-hpc-rdma-configure (HPC)
      yum:
        name: "{{ hpc_artifacts_download }}oci-hpc-rdma-configure-{{ oci_hpc_rdma_configure_version }}-compute.el7.noarch.rpm"
        state: present
        disable_gpg_check: yes

    - name: Install oci-hpc-network-device-names (HPC)
      yum:
        name: "{{ hpc_artifacts_download }}oci-hpc-network-device-names-{{ oci_hpc_network_device_names_version }}-compute.el7.noarch.rpm"
        state: present
        disable_gpg_check: yes

    - name: Install oci-hpc-dapl-configure (HPC)
      yum:
        name: "{{ hpc_artifacts_download }}oci-hpc-dapl-configure-{{ oci_hpc_dapl_configure_version }}-compute.el7.noarch.rpm"
        state: present
        disable_gpg_check: yes

  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '7'


- name: OCI HPC packages for Ubuntu 20
  block:

    - name: Ensure ifupdown is present
      apt:
        pkg: ifupdown

    - name: Install oci-cn-auth (HPC)
      apt:
        deb: "{{ hpc_artifacts_download }}oci-cn-auth_{{ oci_cn_auth_version }}-compute_all.deb"

    - name: Stop oci-cn-auth renew timer
      systemd:
        name: oci-cn-auth-renew.timer
        state: stopped
        enabled: yes

    - name: Install oci-hpc-mlx-configure (HPC)
      apt:
        deb: "{{ hpc_artifacts_download }}oci-hpc-mlx-configure_{{ oci_hpc_mlx_configure_version }}-compute_all.deb"

    - name: Install oci-hpc-rdma-configure (HPC)
      apt:
        deb: "{{ hpc_artifacts_download }}oci-hpc-rdma-configure_{{ oci_hpc_rdma_configure_version }}-compute_all.deb"

    - name: Install oci-hpc-network-device-names (HPC)
      apt:
        deb: "{{ hpc_artifacts_download }}oci-hpc-network-device-names_{{ oci_hpc_network_device_names_version }}-compute_all.deb"

    - name: Install oci-hpc-dapl-configure (HPC)
      apt:
        deb: "{{ hpc_artifacts_download }}oci-hpc-dapl-configure_{{ oci_hpc_dapl_configure_version }}-compute_all.deb"

  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '20'
